# Generated by Django 3.1.7 on 2021-03-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
