# Generated by Django 3.1.7 on 2021-03-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='lastReviewed',
            new_name='last_reviewed_at',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='nextReviewDate',
            new_name='next_reviewed_at',
        ),
    ]
