# Generated by Django 3.1.7 on 2021-03-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20210316_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='next_reviewed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
