# Generated by Django 3.1.7 on 2021-03-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20210316_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bucket',
            field=models.IntegerField(choices=[(1, '1 Day'), (2, '3 Days'), (3, '7 Days'), (4, '16 Days'), (5, '30 Days')], default=1),
        ),
    ]
